Testing
rsnazario/Proj2_Enumerable_Method pull request #3
Opened 2020-03-24 19:55 UTC by rsnazario

Follow Map of the Testing 
 
  - Added Rspec files
  - Added structure of rspec testing for the methods
  - Added comparison to the main tests of the ruby-documentation
  - Applied rubocop checking

2020-03-24 21:27 UTC, mosesogwo requested changes
**Hello, good work with testing this project :+1: See my comments for the required changes.**

Also, add test for your multiply_els method.


_**Kindly make the changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-03-24 21:27 UTC, mosesogwo commented on spec/enum_methods_spec.rb
> +  let(:arr_3) { ['cat', 3, true, 'board'] }
arr_3 is not used anywhere in the test. It should be removed.

2020-03-24 21:27 UTC, mosesogwo commented on spec/enum_methods_spec.rb
> +    context 'if argument is Regular expression return true if all objects contain it' do
Add test for the converse of this context - when not all the objects match the regex

2020-03-24 21:27 UTC, mosesogwo commented on spec/enum_methods_spec.rb
> +    context 'if argument is Class return true if all objects are of that class' do
Add test for the converse of this context - when not all the objects are of that class

2020-03-24 21:27 UTC, mosesogwo commented on spec/enum_methods_spec.rb
> +    context 'if argument is Regular expression return true if any objects contain it' do
Add test for the converse of this context.

2020-03-24 21:27 UTC, mosesogwo commented on spec/enum_methods_spec.rb
> +    context 'if argument is Class return true if any object is of that class' do
Add test for the converse of this context.

2020-03-24 21:27 UTC, mosesogwo commented on spec/enum_methods_spec.rb
> +    context 'if argument is Regular expression return false if all any value of object contains it' do
Add test for the converse of this context.

2020-03-24 21:27 UTC, mosesogwo commented on spec/enum_methods_spec.rb
> +    context 'if argument is Class return true if all any value of object is not of that class' do
Add test for the converse of this context.

2020-03-24 21:27 UTC, mosesogwo commented on spec/enum_methods_spec.rb
> +      it { expect(arr_1.my_each_with_index).to be_a(Enumerator) }
You're testing for my_each_with_index instead of my_map

2020-03-25 00:38 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @rsnazario and @Elbie-em :balloon: :lollipop: 

### Thank you for doing the changes requested by the previous reviewer I can see you did a good amount of research, :medal_sports:  You've added a good amount of test cases so your project is good to pass  :heavy_check_mark: 

[OPTIONAL]

- [ ] I won't stop you from moving forward for this but in the test cases you have for example

```ruby
expect (value).to eq(false)
```
you could also validate like this:
```ruby
expect(value).not_to eq(true)
```
### Please :pray: do the optional changes (or not) :man_technologist: :man_technologist: and merge this branch always checking all your test cases pass :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru**

PROJECT STATUS: APPROVED :green_apple:

2020-03-25 00:38 UTC, euqueme commented on spec/enum_methods_spec.rb
> +      hash = {}
[OPTIONAL]
- [ ] Define the hash variable on line #25 also like a let variable within the '#my_each_with_index' block

2020-03-25 01:05 UTC, merged